apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: ros-gem-job
spec:
  containers:
  - name: docker
    image: docker:24.0.7-dind
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
